insert into ComicEntity (id, nombre, autor, anioSalida, perteneceColeccion, perteneceSerie, precio, tema, enVenta, informacion, imagen) values (1, 'The X-Men','El viejo Stan', 1930, 0, 0, 61.59,1,1, 'El Cómic de X-Men, o también conocidos como Patrulla-X, son un grupo de superhéroes del Universo Marvel creado por Stan Lee y Jack Kirby', 'comic4.jpg');
insert into ComicEntity (id, nombre, autor, anioSalida, perteneceColeccion, perteneceSerie, precio, tema, enVenta, informacion, imagen) values (2, 'The Avengers', 'Stan Lee', 1994, 0, 0, 2.69, 3.6, 1, 'DEl equipo de superhéroes de Marvel cuenta con el gran reparto de los personajes más característicos y carismáticos de la historia del cómic', 'comic3.jpg');
insert into ComicEntity (id, nombre, autor, anioSalida, perteneceColeccion, perteneceSerie, precio, tema, enVenta, informacion, imagen) values (3, 'The Amazing spiderman', 'Stan Lee', 2007, 1, 0, 67.01, 6.8, 0, 'With six, you get chaos! While still in high school, the Amazing Spider-Man faced one of his most chilling challenges when', 'comicp2.jpg');
insert into ComicEntity (id, nombre, autor, anioSalida, perteneceColeccion, perteneceSerie, precio, tema, enVenta, informacion, imagen) values (4, 'Thanos', 'Tini Howard', 1971, 0, 1, 97.34, 10.61, 1, 'THANOS IS DEAD! Executed by the deadliest assassin in the galaxy - his daughter, Gamora. But before their relationship came to a bloody end, how did it begin?', 'comic2.jpg');
insert into ComicEntity (id, nombre, autor, anioSalida, perteneceColeccion, perteneceSerie, precio, tema, enVenta, informacion, imagen) values (5, 'Superman', 'Marsha Andrat', 1905, 1, 0, 84.13, 5.64, 1, 'El héroe más poderoso y carismático del mundo, Superman, llegó desde el planeta Krypton con la misión de quedarse en el Planeta Tierra', 'comicp1.jpg');
insert into ComicEntity (id, nombre, autor, anioSalida, perteneceColeccion, perteneceSerie, precio, tema, enVenta, informacion, imagen) values (6, 'Old man Logan', 'Adrian Wych', 1968, 1, 1, 11.42, 4.36, 1, 'El equipo creativo de la monumental Civil War, regresa para narrarte una epopeya apocalíptica', 'comicp3.jpg');
insert into ComicEntity (id, nombre, autor, anioSalida, perteneceColeccion, perteneceSerie, precio, tema, enVenta, informacion, imagen) values (7, 'Thor', 'Marcellus Hartzog', 1953, 0, 0, 35.57, 5.81, 1, 'Odin el padre de todos, sabia que Asgard estaba destinada a ser destruida por el ciclo infinito de Ragnarok', 'comicp4.jpg');
insert into ComicEntity (id, nombre, autor, anioSalida, perteneceColeccion, perteneceSerie, precio, tema, enVenta, informacion, imagen) values (8, 'Civil War', 'Winnah Kensitt', 1955, 0, 0, 48.24, 10.35, 1, 'After a horrific tragedy raises questions on whether or not super heroes should register with the government', 'comic5.jpg');
insert into ComicEntity (id, nombre, autor, anioSalida, perteneceColeccion, perteneceSerie, precio, tema, enVenta, informacion, imagen) values (9, 'The incredible Hulk', 'Ingemar Barkway', 1956, 1, 0, 22.34, 11.76, 1, 'Shadow Base has declared total war on Bruce Banner — and one by one, death is touching everyone he ever knew', 'comic6.jpg');
insert into ComicEntity (id, nombre, autor, anioSalida, perteneceColeccion, perteneceSerie, precio, tema, enVenta, informacion, imagen) values (10, 'Black Panther', 'Marne Siddle', 1978, 1, 1, 91.96, 9.94, 1, 'T Challa is the Black Panther – a righteous king, noble Avenger, and fearsome warrior. ', 'comic7.jpg');
insert into ComicEntity (id, nombre, autor, anioSalida, perteneceColeccion, perteneceSerie, precio, tema, enVenta, informacion, imagen) values (11, 'Ironman', 'Pru Dreng', 2009, 0, 0, 48.81, 1.39, 1, 'The gleaming Golden Avenger steals the show as we celebrate the 80th anniversary of the House of Ideas', 'comic8.jpg');
insert into ComicEntity (id, nombre, autor, anioSalida, perteneceColeccion, perteneceSerie, precio, tema, enVenta, informacion, imagen) values (12, 'Hawk and Dove', 'Godwin Dossantos', 1977, 0, 1, 49.59, 8.97, 1, 'War of the Gods Part 7. Final issue. Hawk and Dove come to terms with who they are and what they expect to be...even if finding happiness requires a parting of the ways.', 'comic10.jpg');

select * from ComicEntity;


