

insert into CompradorEntity(id, alias, email, intereses, nombre, foto) values (100,'heavyRock','juan@hotmail.com','Musica','Juan Pedro', 'http://www.esvivir.com/uploads/eres_persona_motivada_711_26121651.jpg');
insert into CompradorEntity(id, alias, email, intereses, nombre, foto) values (200,'mariaDB','maria@yahoo.com','Juegos','Maria Davalos','');
insert into CompradorEntity(id, alias, email, intereses, nombre, foto) values (300,'lucyLane','lucia@gmail.com','Manga','Lucia Lane','');
insert into CompradorEntity(id, alias, email, intereses, nombre, foto) values (400,'tobiasForge','tobias@outlook.com','Anime','Tobias Forge','');
insert into CompradorEntity(id, alias, email, intereses, nombre, foto) values (500,'heroeSilencio','enrique@uniandes.edu.co','Heroes','Enrique Bunbury','');
insert into CompradorEntity(id, alias, email, intereses, nombre, foto) values (600,'locoAsesino','marcos@hotmail.com','Marvel','Marco Aurelio','https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Marcus_Aurelius_Glyptothek_Munich.jpg/245px-Marcus_Aurelius_Glyptothek_Munich.jpg');
insert into CompradorEntity(id, alias, email, intereses, nombre, foto) values (700,'bebecito','bebecito@hotmail.com','DC Comics','Bebecito','');
insert into CompradorEntity(id, alias, email, intereses, nombre, foto) values (800,'sherlockHolmes','sherlock@hotmail.com','Terror','Sherlock Holmes','https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Statue_of_Sherlock_Holmes_in_Edinburgh.jpg/180px-Statue_of_Sherlock_Holmes_in_Edinburgh.jpg');

insert into vendedorentity (id, alias, email, foto, intereses, nombre, password) values (1, 'lmagnus0', 'lmagnus0@angelfire.com', 'https://robohash.org/utquisnon.png?size=500x500&set=set1', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'Lyda Magnus', 'c9rilgcNR');
insert into vendedorentity (id, alias, email, foto, intereses, nombre, password) values (2, 'asmithe1', 'asmithe1@foxnews.com', 'https://robohash.org/suntlaborumid.jpg?size=500x500&set=set1', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'Alessandro Smithe', 'oJEh2V');
insert into vendedorentity (id, alias, email, foto, intereses, nombre, password) values (3, 'sneave2', 'sneave2@bloomberg.com', 'https://robohash.org/laboriosamnisinemo.bmp?size=500x500&set=set1', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Shaylyn Neave', 'M1Iexfq');
insert into vendedorentity (id, alias, email, foto, intereses, nombre, password) values (4, 'jwallentin3', 'jwallentin3@twitpic.com', 'https://robohash.org/harumquiquia.bmp?size=500x500&set=set1', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'Jania Wallentin', 'LGEUgX1zYH');
insert into vendedorentity (id, alias, email, foto, intereses, nombre, password) values (5, 'phalesworth4', 'phalesworth4@t-online.de', 'https://robohash.org/iureofficiaet.png?size=500x500&set=set1', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'Patrizio Halesworth', 'WgTqHoV');
insert into vendedorentity (id, alias, email, foto, intereses, nombre, password) values (6, 'esutherington5', 'esutherington5@elegantthemes.com', 'https://robohash.org/animietet.bmp?size=500x500&set=set1', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'Elsy Sutherington', 'r7Q4Cl09xD');
insert into vendedorentity (id, alias, email, foto, intereses, nombre, password) values (7, 'eganter6', 'eganter6@jimdo.com', 'https://robohash.org/quisquamipsaquidem.jpg?size=500x500&set=set1', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'Ekaterina Ganter', 'oWzAZh7Q');
insert into vendedorentity (id, alias, email, foto, intereses, nombre, password) values (8, 'rmarguerite7', 'rmarguerite7@blogtalkradio.com', 'https://robohash.org/iurequiaeaque.png?size=500x500&set=set1', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 'Roana Marguerite', '51zeC1B0mM');
insert into vendedorentity (id, alias, email, foto, intereses, nombre, password) values (9, 'bthexton8', 'bthexton8@cbsnews.com', 'https://robohash.org/ipsumexassumenda.bmp?size=500x500&set=set1', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'Brina Thexton', '0CdwNr7W');
insert into vendedorentity (id, alias, email, foto, intereses, nombre, password) values (10, 'cpopham9', 'cpopham9@icio.us', 'https://robohash.org/aliquidexplicaboneque.png?size=500x500&set=set1', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'Clarisse Popham', 'IBdhV2PlJrHQ');
insert into vendedorentity (id, alias, email, foto, intereses, nombre, password) values (11, 'rkelwaybambera', 'rkelwaybambera@4shared.com', 'https://robohash.org/doloremvelitmolestiae.png?size=500x500&set=set1', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Rutledge Kelwaybamber', 'CfOxdVoL0');
insert into vendedorentity (id, alias, email, foto, intereses, nombre, password) values (12, 'kswalwelb', 'kswalwelb@time.com', 'https://robohash.org/occaecatiquaequi.png?size=500x500&set=set1', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'Kellsie Swalwel', '7zj61yAMb7Q');
insert into vendedorentity (id, alias, email, foto, intereses, nombre, password) values (13, 'bcollecottc', 'bcollecottc@loc.gov', 'https://robohash.org/temporibussolutacorrupti.bmp?size=500x500&set=set1', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'Bonita Collecott', 'pl3wLHnhY');
insert into vendedorentity (id, alias, email, foto, intereses, nombre, password) values (14, 'cslowgroved', 'cslowgroved@yelp.com', 'https://robohash.org/aliquiddolorcommodi.bmp?size=500x500&set=set1', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'Carmencita Slowgrove', 'xFma68Qp3vR');
insert into vendedorentity (id, alias, email, foto, intereses, nombre, password) values (15, 'oduxbarrye', 'oduxbarrye@imgur.com', 'https://robohash.org/quisipsasint.bmp?size=500x500&set=set1', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'Ofelia Duxbarry', 'oUqvmPX9Dg');
insert into vendedorentity (id, alias, email, foto, intereses, nombre, password) values (16, 'rlonghirstf', 'rlonghirstf@smugmug.com', 'https://robohash.org/officiacumet.png?size=500x500&set=set1', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'Robina Longhirst', 'stzNFrLz');
insert into vendedorentity (id, alias, email, foto, intereses, nombre, password) values (17, 'klivermoreg', 'klivermoreg@yellowbook.com', 'https://robohash.org/rerumutqui.png?size=500x500&set=set1', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'Kristi Livermore', '21BybW6m8');
insert into vendedorentity (id, alias, email, foto, intereses, nombre, password) values (18, 'cpalfrieh', 'cpalfrieh@columbia.edu', 'https://robohash.org/delenitiinciduntadipisci.bmp?size=500x500&set=set1', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'Catriona Palfrie', 'akJu0uJYdK5');
insert into vendedorentity (id, alias, email, foto, intereses, nombre, password) values (19, 'tgerhartzi', 'tgerhartzi@intel.com', 'https://robohash.org/estperferendisnumquam.png?size=500x500&set=set1', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'Tades Gerhartz', '6bjJp00V');
insert into vendedorentity (id, alias, email, foto, intereses, nombre, password) values (20, 'edej', 'edej@free.fr', 'https://robohash.org/abofficiisquia.jpg?size=500x500&set=set1', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'Eustace de Glanville', 'OadVdU');


select * from CalificacionEntity;
select * from VendedorEntity;
delete from CalificacionEntity;
delete from OrdenPedidoEntity;
delete from VendedorEntity;
delete from comicEntity;